name: docs

on:
  push:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build docs
        uses: htfab/tt-gds-action/docs@tt09-dev-x
        with:
          tools-repo: htfab/tt-support-tools
          tools-ref: tt09-dev-x
